image: gitpod/workspace-full

tasks:
  - init: |
      cd /workspace
      git clone https://github.com/KengoTODA/flix-gradle-plugin.git
      cd /workspace/flix-playground
      ./gradlew build

vscode:
  extensions:
    - flix.flix
    - mathiasfrohlich.kotlin
