image: gitpod/workspace-full

tasks:
  - init: |
      cd /workspace
      git clone https://github.com/KengoTODA/flix-gradle-plugin.git
      cd /workspace/flix-playground
      ./gradlew build

vscode:
  extensions:
    - https://github.com/KengoTODA/vscode-flix/releases/download/0.57.0/flix-0.57.0.vsix
    - mathiasfrohlich.kotlin
