on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: |
        curl -L -O https://github.com/flix/flix/releases/download/v0.26.0/flix.jar
        java -jar flix.jar test
    - uses: actions/upload-artifact@v2
      with:
        name: build result
        path: build
